import { Box, Breadcrumbs, Typography } from '@mui/material';
import Head from 'next/head';
import Link from 'next/link';
import React from 'react';
import Header from '../../../components/Home/Header';
import ResHeader from '../../../components/Home/ResHeader';
import Footer from '../../../components/Home/Footer';
import Card from '../../../components/homepts/Card';
import MMA from '../../../public/Assets/home_pts/two-professional-mma-fighters-boxing-isolated-white-studio 1.svg';
import Swimming from '../../../public/Assets/home_pts/strong-caucasian-professional-sportsman-swimmer-training-isolated-white 1.svg';
import Boxing from '../../../public/Assets/home_pts/full-length-portrait-muscular-sportsman-with-prosthetic-leg-copy-space-male-boxer-red-gloves-training-practicing-isolated-white-wall-concept-sport-healthy-lifestyle 1.svg';
import Wrestling from '../../../public/Assets/home_pts/young-man-thai-boxer-training-isolated-white-studio-background-concept-sport 1.svg';
import Fitness from '../../../public/Assets/home_pts/caucasian-professional-male-athlete-runner-training-isolated-white-background 2.svg';
import Yoga from '../../../public/Assets/home_pts/pexels-shvets-production-6975241 1.svg';
import BodyBuilding from '../../../public/Assets/home_pts/close-up-portrait-serious-sweaty-athletic-man-lifting-dumbbell 1.svg';
import SoccerAcademys from '../../../public/Assets/home_pts/lucky-football-player 1.svg';
import Tennis from '../../../public/Assets/home_pts/one-caucasian-man-playing-tennis-player-isolated-white 1.svg';
import TableTennis from '../../../public/Assets/home_pts/athlete-with-disabilities-amputee-isolated-white-professional-male-tennis-player-with-leg-prosthesis-training 1.svg';
import JiuJitsu from '../../../public/Assets/home_pts/two-judokas-fighters-posing-gray 1.svg';
import Shooting from '../../../public/Assets/home_pts/portrait-young-soldier-camouflage-with-gun-white-wall 1.svg';
import Kickboxing from '../../../public/Assets/home_pts/mma-fighters-white-background 1.svg';
import ProfileCard from '../../../components/fitness/Profilecard';
import Marcelo from '../../../public/Assets/home_pts_fitness/Marcelo.svg';
import Lena from '../../../public/Assets/home_pts_fitness/Lena Pereviazkina.svg';
import Hamada from '../../../public/Assets/home_pts_fitness/Hamada Ali.svg';
import Grid from '@mui/material/Unstable_Grid2';
const fitness = ({
  image,
  name,
  description,
  money,
  location,
  languages,
  facebook,
  instagram,
  link,
}) => {
  return (
    <div className="pts w-full  ">
      <Head>
        <title>FIT CORNERZ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../../../public/H_ResLogo.svg" />
      </Head>
      <Header />
      <ResHeader />
      <Grid container md={10} className="mx-auto px-5 md:px-0 pb-10 sm:pb-20">
        <Grid item xs={12} className="py-8  ">
          <Breadcrumbs aria-label="breadcrumb">
            <Link underline="hover" color="inherit" href="/">
              Home
            </Link>
            <Link
              underline="hover"
              color="inherit"
              href="/homepages/fitness/pts"
            >
              PTs
            </Link>
            <Typography color="text.primary">Fitness</Typography>
          </Breadcrumbs>
        </Grid>
        <Grid item xs={12}>
          <Typography className="text-[14px] font-bold text-[#FBAC16]">
            13 CATEGORIES
          </Typography>
          <Typography className="text-[56px] font-bold ">Fitness</Typography>
        </Grid>
        <Grid item xs={12} className="py-3">
          <Typography>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
            ad minim veniam,
          </Typography>
        </Grid>
        <Grid item xs={12} className="py-3">
          <Typography className="text-[18px] underline font-bold text-[#FBAC16]">
            FILTERS (1)
          </Typography>
        </Grid>
        <Grid item xs={12} className="pt-5 pb-16">
          <Grid className="flex flex-col gap-y-5">
            <ProfileCard
              image={Marcelo}
              name="Marcelo Joe Ayala"
              description=" reative fitness professional with more than 25 years of solid
            experience in fitness industry | Certified coach level 2 & 3,
            Rehab specialist level 1."
              location=" Amman, Jordan"
              money="25 JOD/hr"
              languages="Arabic, English"
              facebook="https://www.facebook.com"
              instagram="https://instagram.com"
              link="/homepages/fitness/lenapereviazkina"
            />
            <ProfileCard
              image={Lena}
              name="Lena Pereviazkina"
              description=" Hello,my name is Lena Pereviazkina , I am a Certified Personal Trainer and Nutritional Advisor in Abu Dhabi. Since I have 7 years of experience in this field."
              location=" Amman, Jordan"
              money="25 JOD/hr"
              languages="Arabic, English"
              facebook="https://www.facebook.com"
              instagram="https://instagram.com"
              link="/homepages/fitness/lenapereviazkina"
            />
            <ProfileCard
              image={Hamada}
              name="Hamada Ali"
              description=" Whatever your goal is, I am here to help you to achieve it, and I have a passion for fitness since I was a child. I have the experience-backed since to do that..."
              location=" Amman, Jordan"
              money="25 JOD/hr"
              languages="Arabic, English"
              facebook="https://www.facebook.com"
              instagram="https://instagram.com"
              link="/homepages/fitness/lenapereviazkina"
            />
          </Grid>
        </Grid>
      </Grid>
      <Footer />
    </div>
  );
};

export default fitness;
