import React from 'react';
import Head from 'next/head';
import { Box, Breadcrumbs, Grid, Typography } from '@mui/material';
import ProfileCard from '../../../components/lenapereviazkina/Profilecard';
import Link from 'next/link';
import Header from '../../../components/Home/Header';
import ResHeader from '../../../components/Home/ResHeader';
import Lena from '../../../public/Assets/home_pts_fitness/Lena Pereviazkina.svg';
import Footer from '../../../components/Home/Footer';
const lenapereviazkina = ({
  image,
  name,
  description,
  email,
  phone,
  facebook,
  instagram,
  location,
  money,
  languages,
  routines,
}) => {
  return (
    <div className="">
      <Head>
        <title>FIT CORNERZ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../../../public/H_ResLogo.svg" />
      </Head>
      <Header />
      <ResHeader />
      <Grid container md={10} className="mx-auto px-5 md:px-0 pb-10 sm:pb-20">
        <Grid xs={12} className="py-8  ">
          <Breadcrumbs aria-label="breadcrumb">
            <Link underline="hover" color="inherit" href="/">
              Home
            </Link>
            <Link
              underline="hover"
              color="inherit"
              href="/homepages/fitness/pts"
            >
              PTs
            </Link>
            <Link
              underline="hover"
              color="inherit"
              href="/homepages/fitness/fitness"
            >
              Fitness
            </Link>
            <Typography color="text.primary">Lena Pereviazkina</Typography>
          </Breadcrumbs>
        </Grid>
        <Grid xs={12}>
          <ProfileCard
            image={Lena}
            name="Lena Pereviazkina"
            description=" Hello,my name is Lena Pereviazkina , I am a Certified Personal Trainer and Nutritional Advisor in Abu Dhabi. Since I have 7 years of experience in this field."
            email="LenaPereviazkina@gmail.com"
            phone="+962798907906"
            facebook="https://www.facebook.com"
            instagram="https://instagram.com"
            location="Amman, Jordan"
            languages="Arabic, English"
            money="@% JOD/hr"
            routines="At Home, Outside, Gym, Online"
          />
        </Grid>
      </Grid>
      <Footer />
    </div>
  );
};

export default lenapereviazkina;
