import React from 'react';
import Head from 'next/head';
import Header from '../../../components/home/Header';
import ResHeader from '../../../components/Home/ResHeader';
import Footer from '../../../components/Home/Footer';
import { Box, Grid, Typography } from '@mui/material';
import Skull from '../../../public/Assets/blog-article/skull.svg';
import Image from 'next/image';
import casestudyBImg from '../../../public/Assets/Home/casestudy.jpg';
import videoBImg from '../../../public/Assets/Home/video.jpg';
import articleBImg from '../../../public/Assets/Home/article.jpg';
import BlogCard from '../../../components/home/BlogCard';
const article = ({ blogname, title, description, blogImage, link }) => {
  return (
    <div>
      <Head>
        <title>FIT CORNERZ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../../../public/H_ResLogo.svg" />
      </Head>
      <Header />
      <ResHeader />
      <Grid container xs={10} className="mx-auto">
        <Grid container xs={12} className="py-8">
          <Grid item md={6} className="px-3">
            <Typography className="text-[#FBAC18] text-[14px]">
              ARTICLE
            </Typography>
            <Typography className="md:text-[5vw] text-[9vw] font-bold pb-3">
              Excepteur Sint.
            </Typography>
            <Box>
              <Typography className="sm:text-[20px]  text-[14px] pb-6 pt-3">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
                enim ad minim veniam, quis nostrud exercitation ullamco laboris
                nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor
                in reprehenderit in voluptate velit esse cillum dolore eu fugiat
                nulla pariatur. So if you can understand how to write effective
                copy and understand the purpose that it serves, you`ll be able
                to better serve your clients and ultimately create better
                designs. In this article, we`ll cover some helpful copywriting
                tips for designers to help you build better experiences.
              </Typography>
            </Box>
          </Grid>
          <Grid item md={6} className="flex items-center justify-center">
            <Image
              src={Skull}
              height={400}
              width={400}
              alt="article"
              className="mx-auto"
            />
          </Grid>
        </Grid>
        <Grid container xs={12}>
          <Grid item md={6}>
            <Typography className="md:text-[2vw] text-[20px] font-bold">
              Sales Copywriting vs. UX copywriting
            </Typography>
            <Box>
              <Typography className="sm:text-[20px] md:my-8 my-4 text-[14px]">
                First things first, understand the nature of the copy you`re
                writing for. There are some subtle differences between sales or
                persuasive copywriting and UX writing
              </Typography>

              <li className="sm:text-[20px]  w-auto text-[14px] py-2">
                {' '}
                Why consistent writing makes you a better designer
              </li>

              <li className="sm:text-[20px]  w-auto text-[14px] py-2">
                {' '}
                Why consistent writing makes you a better designer
              </li>

              <li className="sm:text-[20px]  w-auto text-[14px] py-2">
                Why consistent writing makes you a better designer
              </li>

              <Typography className="sm:text-[20px] md:my-8 my-4 text-[14px]">
                First things first, understand the nature of the copy you`re
                writing for. There are some subtle differences between sales or
                persuasive copywriting and UX writing First things first,
                understand the nature of the copy you`re writing for. There are
                some subtle differences between sales or persuasive copywriting
                and UX writing
              </Typography>
            </Box>
            <Grid
              item
              xs={12}
              className="sm:flex flex-wrap py-4 border-gray-300 border-t-2 my-3 gap-y-3 "
            >
              <Box className="sm:w-1/2 mx-auto md:mx-0 ">
                <Typography className="text-[14px]">Founded</Typography>
                <Typography className="text-[35px]">2000</Typography>
              </Box>
              <Box className="sm:w-1/2 mx-auto md:mx-0">
                <Typography className="text-[14px]">Employees</Typography>
                <Typography className="text-[35px]">23K</Typography>
              </Box>
            </Grid>
            <Grid
              item
              xs={12}
              className="sm:flex flex-wrap py-4 border-gray-300 border-t-2 mb-8 gap-y-3"
            >
              <Box className="sm:w-1/2 mx-auto md:mx-0">
                <Typography className="text-[14px]">Customer</Typography>
                <Typography className="text-[35px]">203k</Typography>
              </Box>
              <Box className="sm:w-1/2 mx-auto md:mx-0">
                <Typography className="text-[14px]">Raised</Typography>
                <Typography className="text-[35px]">$409M</Typography>
              </Box>
            </Grid>
          </Grid>
        </Grid>
      </Grid>
      <Grid container xs={12} className="py-6 bg-[#F8F8F8]">
        <Grid item md={10} className="mb-12 mx-auto">
          <Grid
            item
            xs={12}
            className="text-center flex md:mt-0 mt-5 items-center justify-center "
          >
            <h1 className="flex text-[32px] my-6 font-bold md:text-[5.5vw] gap-x-4">
              {' '}
              From Our{' '}
              <span className="flex  text-[32px] md:text-[5.5vw] font-bold  text-[#FBAC18]">
                {' '}
                Blogs
              </span>
            </h1>
          </Grid>
          <Grid
            item
            container
            xs={12}
            className="mx-auto flex items-center justify-evenly gap-y-6"
          >
            <Box className="flex items-center justify-center  sm:w-[55%] md:w-[32%]">
              <BlogCard
                blogImage={casestudyBImg}
                blogname="CASE STUDY"
                title="Sed do eiusmod tempor 8% incididunt ut labore et."
                description="Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu reprehenderit fugiat."
                link="/homepages/blog/article"
              />
            </Box>
            <Box className="flex items-center justify-center sm:w-[55%] md:w-[32%]">
              <BlogCard
                blogImage={videoBImg}
                blogname="VIDEO"
                title="Oed emasn eiusmod tempor incididunt labore et dolor."
                description="Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat،Excepteur sint occaecat cupidatat"
                link="/homepages/blog/article"
              />
            </Box>
            <Box className="flex items-center justify-center  sm:w-[55%] md:w-[32%]">
              <BlogCard
                blogImage={articleBImg}
                blogname="ARTICLE"
                title="Dolor masn eiusmod tempor  labore et occaecat."
                description="Duis aute irure dolor in reprehenderit in voluptate velit esse cillum."
                link="/homepages/blog/article"
              />
            </Box>
          </Grid>
        </Grid>
      </Grid>
      <Footer />
    </div>
  );
};

export default article;
