import React from 'react';
import Head from 'next/head';
import { Box, Breadcrumbs, Grid, Typography } from '@mui/material';
import ProfileCard from '../../../components/publichealthnutritionist/Profilecard';
import Link from 'next/link';
import Header from '../../../components/Home/Header';
import ResHeader from '../../../components/Home/ResHeader';
import Lena from '../../../public/Assets/home_nutritionist_publichealthnutritionist/lena.svg';
import Footer from '../../../components/Home/Footer';
const publichealthnutritionist = ({
  image,
  name,
  description,
  email,
  phone,
  facebook,
  instagram,
  location,
  language,
  link,
}) => {
  return (
    <div className="">
      <Head>
        <title>FIT CORNERZ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../../../public/H_ResLogo.svg" />
      </Head>
      <Header />
      <ResHeader />
      <Grid container md={10} className="mx-auto px-5 md:px-0 pb-10 sm:pb-20">
        <Grid xs={12} className="py-8  ">
          <Breadcrumbs aria-label="breadcrumb">
            <Link underline="hover" color="inherit" href="/">
              Home
            </Link>
            <Link
              underline="hover"
              color="inherit"
              href="/homepages/nutritionist/nutritionist"
            >
              Nutritionist
            </Link>

            <Typography color="text.primary">
              Public Health Nutritionist
            </Typography>
          </Breadcrumbs>
        </Grid>
        <Grid item xs={12}>
          <Typography className="text-[14px] font-bold text-[#FBAC16]">
            23 Nutritionist
          </Typography>
          <Typography className="sm:text-[5vw] text-[30px]  font-bold ">
            Public Health Nutritionist
          </Typography>
        </Grid>
        <Grid item xs={12} className="py-3">
          <Typography>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
            ad minim veniam,
          </Typography>
        </Grid>
        <Grid item xs={12} className="py-3">
          <Typography className="text-[18px] underline font-bold text-[#FBAC16]">
            FILTERS (1)
          </Typography>
        </Grid>
        <Grid xs={12}>
          <ProfileCard
            image={Lena}
            name="Lena Pereviazkina"
            description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim...
            "
            email="LenaPereviazkina@gmail.com"
            phone="+962798907906"
            facebook="https://www.facebook.com"
            instagram="https://instagram.com"
            location="Amman, Jordan"
            languages="Arabic, English"
            link="/homepages/nutritionist/PHNlena"
          />
        </Grid>
      </Grid>
      <Footer />
    </div>
  );
};

export default publichealthnutritionist;
