import React from 'react';
import Head from 'next/head';
import { Box, Breadcrumbs, Grid, Typography } from '@mui/material';
import ProfileCard from '../../../components/bodybuilding/Profilecard';
import Link from 'next/link';
import Header from '../../../components/Home/Header';
import ResHeader from '../../../components/Home/ResHeader';
import BodyBuilding from '../../../public/Assets/home_gym_bodybuilding/gymslogo.svg';
import Footer from '../../../components/Home/Footer';
const bodybuilding = ({
  image,
  name,
  description,
  email,
  phone,
  facebook,
  instagram,
  location,
  sex,
  link,
}) => {
  return (
    <div className="">
      <Head>
        <title>FIT CORNERZ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../../../public/H_ResLogo.svg" />
      </Head>
      <Header />
      <ResHeader />
      <Grid container md={10} className="mx-auto px-5 md:px-0 pb-10 sm:pb-20">
        <Grid xs={12} className="py-8  ">
          <Breadcrumbs aria-label="breadcrumb">
            <Link underline="hover" color="inherit" href="/">
              Home
            </Link>
            <Link underline="hover" color="inherit" href="/homepages/gym/gym">
              Gym
            </Link>

            <Typography color="text.primary">Bodybuilding</Typography>
          </Breadcrumbs>
        </Grid>
        <Grid item xs={12}>
          <Typography className="text-[14px] font-bold text-[#FBAC16]">
            23 Gyms
          </Typography>
          <Typography className="text-[56px] font-bold ">
            Body Building
          </Typography>
        </Grid>
        <Grid item xs={12} className="py-3">
          <Typography>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
            ad minim veniam,
          </Typography>
        </Grid>
        <Grid item xs={12} className="py-3">
          <Typography className="text-[18px] underline font-bold text-[#FBAC16]">
            FILTERS (1)
          </Typography>
        </Grid>
        <Grid xs={12}>
          <ProfileCard
            image={BodyBuilding}
            name="Gold's gym"
            description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim...
            "
            email="LenaPereviazkina@gmail.com"
            phone="+962798907906"
            facebook="https://www.facebook.com"
            instagram="https://instagram.com"
            location="Amman, Jordan"
            sex="Male, Female"
            link="/homepages/gym/goldgym"
          />
        </Grid>
      </Grid>
      <Footer />
    </div>
  );
};

export default bodybuilding;
