import React from 'react';
import Head from 'next/head';
import { Box, Breadcrumbs, Grid, Typography } from '@mui/material';
import ProfileCard from '../../../components/goldgym/Profilecard';
import Link from 'next/link';
import Header from '../../../components/Home/Header';
import ResHeader from '../../../components/Home/ResHeader';
import BodyBuilding from '../../../public/Assets/home_gym_bodybuilding/gymslogo.svg';
import Footer from '../../../components/Home/Footer';
const goldgym = ({
  image,
  name,
  description,
  email,
  phone,
  facebook,
  instagram,
  location,
  sex,
}) => {
  return (
    <div className="">
      <Head>
        <title>FIT CORNERZ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../../../public/H_ResLogo.svg" />
      </Head>
      <Header />
      <ResHeader />
      <Grid container md={10} className="mx-auto px-5 md:px-0 pb-10 sm:pb-20">
        <Grid xs={12} className="py-8  ">
          <Breadcrumbs aria-label="breadcrumb">
            <Link underline="hover" color="inherit" href="/">
              Home
            </Link>
            <Link underline="hover" color="inherit" href="/homepages/gym/gym">
              Gym
            </Link>
            <Link
              underline="hover"
              color="inherit"
              href="/homepages/gym/bodybuilding"
            >
              Bodybuilding
            </Link>
            <Typography color="text.primary">Gold`s Gym</Typography>
          </Breadcrumbs>
        </Grid>
        <Grid xs={12}>
          <ProfileCard
            image={BodyBuilding}
            name="Gold's Gym"
            description=" Hello,my name is Jordan knights , I am a Certified Personal Trainer and Nutritional Advisor in Abu Dhabi. Since I have 7 years of experience in this field."
            email="Jordanknights@gmail.com"
            phone="+962798907906"
            facebook="https://www.facebook.com"
            instagram="https://instagram.com"
            location="Amman, Jordan"
            sex="Male, Female"
          />
        </Grid>
      </Grid>
      <Footer />
    </div>
  );
};

export default goldgym;
