import { Box, Card, Paper, Typography } from '@mui/material';
import Grid from '@mui/material/Unstable_Grid2';
import Image from 'next/image';
import Head from 'next/head';
import casestudyBImg from '../public/Assets/Home/casestudy.jpg';
import videoBImg from '../public/Assets/Home/video.jpg';
import articleBImg from '../public/Assets/Home/article.jpg';
import HeaderJsx from '../components/home/Header';
import ResponsiveHeaderJsx from '../components/home/ResHeader';
import Footer from '../components/home/Footer';
import BlogCard from '../components/home/BlogCard';
const Blogs = ({ blogname, title, description, blogImage, link }) => {
  return (
    <div className="blogs w-full flex flex-col items-center justify-center">
      <Head>
        <title>FIT CORNERZ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./H_ResLogo.svg" />
      </Head>
      <HeaderJsx />
      <ResponsiveHeaderJsx />

      <Grid container md={10} className="mb-12">
        <Grid
          item
          xs={12}
          className="text-center flex md:mt-0 mt-5 items-center justify-center "
        >
          <h1 className="flex text-[32px] my-6 font-bold md:text-[5.5vw] gap-x-4">
            {' '}
            From Our{' '}
            <span className="flex  text-[32px] md:text-[5.5vw] font-bold  text-[#FBAC18]">
              {' '}
              Blogs
            </span>
          </h1>
        </Grid>
        <Grid
          item
          container
          xs={12}
          className="mx-auto flex items-center justify-evenly gap-y-6"
        >
          <Box className="flex items-center justify-center  sm:w-[55%] md:w-[32%]">
            <BlogCard
              blogImage={casestudyBImg}
              blogname="CASE STUDY"
              title="Sed do eiusmod tempor 8% incididunt ut labore et."
              description="Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu reprehenderit fugiat."
              link="/homepages/blog/article"
            />
          </Box>
          <Box className="flex items-center justify-center sm:w-[55%] md:w-[32%]">
            <BlogCard
              blogImage={videoBImg}
              blogname="VIDEO"
              title="Oed emasn eiusmod tempor incididunt labore et dolor."
              description="Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat،Excepteur sint occaecat cupidatat"
              link="/homepages/blog/article"
            />
          </Box>
          <Box className="flex items-center justify-center  sm:w-[55%] md:w-[32%]">
            <BlogCard
              blogImage={articleBImg}
              blogname="ARTICLE"
              title="Dolor masn eiusmod tempor  labore et occaecat."
              description="Duis aute irure dolor in reprehenderit in voluptate velit esse cillum."
              link="/homepages/blog/article"
            />
          </Box>
        </Grid>
      </Grid>
      <Footer />
    </div>
  );
};

export default Blogs;
