import { Box, Grid, Typography } from '@mui/material';
import React from 'react';
import Head from 'next/head';
import HeaderJsx from '../components/home/Header';
import ResponsiveHeaderJsx from '../components/home/ResHeader';
import Table from '@mui/material/Table';
import TableBody from '@mui/material/TableBody';
import TableCell from '@mui/material/TableCell';
import TableContainer from '@mui/material/TableContainer';
import TableHead from '@mui/material/TableHead';
import TableRow from '@mui/material/TableRow';
import Footer from '../components/home/Footer';
import { FormControl } from '@mui/material';
import { InputLabel, Button } from '@mui/material';
import TextField from '@mui/material/TextField';
import RadioGroup from '@mui/material/RadioGroup';
import FormLabel from '@mui/material/FormLabel';
import Radio from '@mui/material/Radio';
import FormControlLabel from '@mui/material/FormControlLabel';
import { createTheme } from '@mui/material/styles';
import Link from 'next/link';
const theme = createTheme({
  palette: {
    primary: {
      main: '#FBAC18',
    },
  },
});
const BMI = () => {
  const tablerangedata = {
    ServereThiness: '< 16',
    ModerateThinness: '16 - 17',
    MildThinness: '17 - 18.5',
    Normal: '18.5 - 25',
    OverWeight: '25 - 30',
    ObeseClassI: '30 - 35',
    ObeseClassII: '35 - 40',
    ObeseClassIII: ' > 40',
  };
  const tablepercentagedata = {
    Underweight: '< 5%',
    Healthyweight: '5% - 8%',
    Risk: '85% - 95%',
    Overweight: '> 95%',
  };
  return (
    <div className="bmi">
      <Head>
        <title>FIT CORNERZ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./H_ResLogo.svg" />
      </Head>
      <ResponsiveHeaderJsx />
      <HeaderJsx />

      <Grid container xs={10} className="mx-auto">
        <h1 className="md:text-[5vw] text-[30px] font-bold py-8  text-bold ">
          Body Mass Index <span className="text-[#FBAC18]">(BMI)</span>{' '}
          Calculator
        </h1>
        <p className="sm:text-[16px] text-[12px]">
          Please fill this information to calculate your BMI
        </p>
        <Box className="w-full">
          <BMIForm />
        </Box>

        <h1 className="sm:text-[24px] text-[18px] font-bold py-6 w-full">
          BMI Introduction
        </h1>
        <p className="sm:text-[16px] text-[12px]">
          BMI is a measurement of a person`s leanness or corpulence based on
          their height and weight, and is intended to quantify tissue mass. It
          is widely used as a general indicator of whether a person has a
          healthy body weight for their height. Specifically, the value obtained
          from the calculation of BMI is used to categorize whether a person is
          underweight, normal weight, overweight, or obese depending on what
          range the value falls between. These ranges of BMI vary based on
          factors such as region and age, and are sometimes further divided into
          subcategories such as severely underweight or very severely obese.
          Being overweight or underweight can have significant health effects,
          so while BMI is an imperfect measure of healthy body weight, it is a
          useful indicator of whether any additional testing or action is
          required. Refer to the table below to see the different categories
          based on BMI that are used by the calculator.
        </p>
      </Grid>
      <Grid container xs={10} className="mx-auto mb-10">
        <Grid md={6}>
          <h1 className="sm:text-[24px] text-[18px]  font-bold py-6 w-full">
            BMI table for adults
          </h1>
          <p className="sm:text-[16px] text-[12px]">
            This is the World Health Organization`s (WHO) recommended body
            weight based on BMI values for adults. It is used for both men and
            women, age 18 or older.{' '}
          </p>

          <Box className="md:w-[90%] md:hidden flex flex-col md:mt-20 mt-8">
            <Table className="w-full">
              <TableHead>
                <TableRow className="bg-gray-300">
                  <TableCell className="sm:text-[16px] text-[12px]">
                    Category
                  </TableCell>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    BMI range- kg/m2
                  </TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                <TableRow className="">
                  <TableCell className="sm:text-[16px] text-[12px]">
                    Servere Thinness
                  </TableCell>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    {' '}
                    {tablerangedata.ServereThiness}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    Moderate Thinness
                  </TableCell>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    {tablerangedata.ModerateThinness}
                  </TableCell>
                </TableRow>
                <TableRow>
                  {' '}
                  <TableCell className="sm:text-[16px] text-[12px]">
                    Mild Thinness
                  </TableCell>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    {tablerangedata.MildThinness}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    Normal
                  </TableCell>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    {tablerangedata.Normal}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    OverWeight
                  </TableCell>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    {tablerangedata.OverWeight}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    Obese Class I
                  </TableCell>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    {tablerangedata.ObeseClassI}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    Obese Class II
                  </TableCell>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    {tablerangedata.ObeseClassII}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    Obese Class III
                  </TableCell>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    {tablerangedata.ObeseClassIII}
                  </TableCell>
                </TableRow>
              </TableBody>
            </Table>
            <Typography className="text-gray-400 text-[12px] mr-auto">
              BMI table for adults
            </Typography>
          </Box>
          <h1 className="sm:text-[24px] text-[18px] font-bold py-6 w-full">
            BMI table for children and teens, age 2-20
          </h1>
          <p className="sm:text-[16px] text-[12px]">
            The Centers for Disease Control and Prevention (CDC) recommends BMI
            categorization for children and teens between age 2 and 20.
          </p>
          <Box className="md:w-[90%] md:hidden flex-col flex mt-8 ">
            <Table className="w-full">
              <TableHead>
                <TableRow className="bg-gray-300">
                  <TableCell className="sm:text-[16px] text-[12px]">
                    Category
                  </TableCell>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    Percentile Range
                  </TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                <TableRow>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    Underweight
                  </TableCell>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    {' '}
                    {tablepercentagedata.Underweight}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    Healthy weight
                  </TableCell>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    {tablepercentagedata.Healthyweight}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    At risk of overweight
                  </TableCell>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    {tablepercentagedata.Risk}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    Overweight
                  </TableCell>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    {tablepercentagedata.Overweight}
                  </TableCell>
                </TableRow>
              </TableBody>
            </Table>
            <Typography className="text-[12px] text-gray-400 mr-auto ">
              {' '}
              BMI table for children and teens{' '}
            </Typography>
          </Box>
          <h1 className="sm:text-[24px] text-[18px] font-bold py-6 w-full">
            Risks associated with being overweight
          </h1>
          <p className="sm:text-[16px] text-[12px]">
            Being overweight increases the risk of a number of serious diseases
            and health conditions. Below is a list of said risks, according to
            the Centers for Disease Control and Prevention (CDC):
          </p>
          <li className="mt-3 sm:text-[16px] text-[12px]">
            High blood pressure
          </li>
          <li className="mt-3 sm:text-[16px] text-[12px]">
            Higher levels of LDL cholesterol, which is widely considered ``bad
            cholesterol,`` lower levels of HDL cholesterol, considered to be
            good cholesterol in moderation, and high levels of triglycerides
          </li>
          <li className="mt-3 sm:text-[16px] text-[12px]">Type II diabetes</li>
          <li className="mt-3 sm:text-[16px] text-[12px]">Stroke</li>
          <li className="mt-3 sm:text-[16px] text-[12px]">
            Gallbladder disease
          </li>
          <li className="mt-3 sm:text-[16px] text-[12px]">
            Osteoarthritis, a type of joint disease caused by breakdown of joint
            cartilage
          </li>
          <li className="mt-3 sm:text-[16px] text-[12px]">
            Sleep apnea and breathing problems
          </li>
          <li className="mt-3 sm:text-[16px] text-[12px]">
            Certain cancers (endometrial, breast, colon, kidney, gallbladder,
            liver)
          </li>
          <li className="mt-3 sm:text-[16px] text-[12px]">
            Low quality of life
          </li>
          <li className="mt-3 sm:text-[16px] text-[12px]">
            Mental illnesses such as clinical depression, anxiety, and others
          </li>
          <li className="mt-3 sm:text-[16px] text-[12px]">
            Body pains and difficulty with certain physical functions
          </li>
          <h1 className="sm:text-[24px] text-[18px] font-bold my-4 w-full">
            Risks associated with being underweight
          </h1>
          <p className="sm:text-[16px] text-[12px]">
            In some cases, being underweight can be a sign of some underlying
            condition or disease such as anorexia nervosa, which has its own
            risks. Consult your doctor if you think you or someone you know is
            underweight, particularly if the reason for being underweight does
            not seem obvious.
          </p>
          <li className="mt-3 sm:text-[16px] text-[12px]">
            Malnutrition, vitamin deficiencies, anemia (lowered ability to carry
            blood vessels)
          </li>
          <li className="mt-3 sm:text-[16px] text-[12px]">
            Osteoporosis, a disease that causes bone weakness, increasing the
            risk of breaking a bone
          </li>
          <li className="mt-3 sm:text-[16px] text-[12px]">
            A decrease in immune function
          </li>
          <li className="mt-3 sm:text-[16px] text-[12px]">
            Growth and development issues, particularly in children and
            teenagers
          </li>
          <li className="mt-3 sm:text-[16px] text-[12px]">
            Possible reproductive issues for women due to hormonal imbalances
            that can disrupt the menstrual cycle. Underweight women also have a
            higher chance of miscarriage in the first trimester
          </li>
          <li className="mt-3 sm:text-[16px] text-[12px]">
            Possible reproductive issues for women due to hormonal imbalances
            that can disrupt the menstrual cycle. Underweight women also have a
            higher chance of miscarriage in the first trimester
          </li>
        </Grid>
        <Grid md={6} className="flex flex-col items-center justify-start">
          <Box className="md:w-[90%] md:flex flex-col hidden md:mt-20 mt-8">
            <Table className="w-full">
              <TableHead>
                <TableRow className="bg-gray-300">
                  <TableCell className="sm:text-[16px] text-[12px]">
                    Category
                  </TableCell>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    BMI range- kg/m2
                  </TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                <TableRow className="">
                  <TableCell className="sm:text-[16px] text-[12px]">
                    Servere Thinness
                  </TableCell>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    {' '}
                    {tablerangedata.ServereThiness}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    Moderate Thinness
                  </TableCell>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    {tablerangedata.ModerateThinness}
                  </TableCell>
                </TableRow>
                <TableRow>
                  {' '}
                  <TableCell className="sm:text-[16px] text-[12px]">
                    Mild Thinness
                  </TableCell>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    {tablerangedata.MildThinness}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    Normal
                  </TableCell>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    {tablerangedata.Normal}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    OverWeight
                  </TableCell>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    {tablerangedata.OverWeight}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    Obese Class I
                  </TableCell>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    {tablerangedata.ObeseClassI}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    Obese Class II
                  </TableCell>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    {tablerangedata.ObeseClassII}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    Obese Class III
                  </TableCell>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    {tablerangedata.ObeseClassIII}
                  </TableCell>
                </TableRow>
              </TableBody>
            </Table>
            <Typography className="text-gray-400 text-[12px] mr-auto">
              BMI table for adults
            </Typography>
          </Box>
          <Box className="md:w-[90%] md:flex hidden  flex-col mt-8 ">
            <Table className="w-full">
              <TableHead>
                <TableRow className="bg-gray-300">
                  <TableCell className="sm:text-[16px] text-[12px]">
                    Category
                  </TableCell>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    Percentile Range
                  </TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                <TableRow>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    Underweight
                  </TableCell>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    {' '}
                    {tablepercentagedata.Underweight}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    Healthy weight
                  </TableCell>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    {tablepercentagedata.Healthyweight}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    At risk of overweight
                  </TableCell>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    {tablepercentagedata.Risk}
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    Overweight
                  </TableCell>
                  <TableCell className="sm:text-[16px] text-[12px]">
                    {tablepercentagedata.Overweight}
                  </TableCell>
                </TableRow>
              </TableBody>
            </Table>
            <Typography className="text-[12px] text-gray-400 mr-auto ">
              {' '}
              BMI table for children and teens{' '}
            </Typography>
          </Box>
        </Grid>
      </Grid>
      <Footer />
    </div>
  );
};

const BMIForm = () => {
  return (
    <>
      <Box className=" md:w-[70%] w-full my-8  ">
        <Box className="w-full flex md:flex-row flex-col md:items-center justify-between">
          <Box className="flex flex-col md:w-[48%] mt-2 md:mt-0">
            <FormLabel className="md:py-3 py-1 text-black font-bold">
              Age
            </FormLabel>
            <TextField label="2 - 100" variant="outlined" />
          </Box>
          <Box className="flex flex-col md:w-[48%] mt-2 md:mt-0">
            <FormLabel className="text-black font-bold">Gender</FormLabel>
            <RadioGroup defaultValue="female" name="radio-buttons-group">
              <FormControlLabel
                value="female"
                control={
                  <Radio
                    className="text-[#FBAC18]"
                    sx={{
                      color: '#FBAC18',
                      '&.Mui-checked': {
                        color: '#FBAC18',
                      },
                    }}
                  />
                }
                label="Female"
              />
              <FormControlLabel
                value="male"
                control={
                  <Radio
                    className="text-[#FBAC18]"
                    sx={{
                      color: '#FBAC18',
                      '&.Mui-checked': {
                        color: '#FBAC18',
                      },
                    }}
                  />
                }
                label="Male"
              />
            </RadioGroup>
          </Box>
        </Box>
        <Box className="w-full flex md:items-center justify-between md:flex-row flex-col">
          <Box className="flex flex-col md:w-[48%]  md:mt-0">
            <FormLabel className="md:py-3 py-1 text-black font-bold">
              Age
            </FormLabel>
            <TextField label="2 - 100" variant="outlined" />
          </Box>
          <Box className="flex flex-col md:w-[48%] mt-2 md:mt-0">
            <FormLabel className="md:py-3 py-1 text-black font-bold">
              Age
            </FormLabel>
            <TextField label="2 - 100" variant="outlined" />
          </Box>
        </Box>
        <Box className="w-full flex md:items-center justify-between md:flex-row flex-col">
          <Box className="flex flex-col md:w-[48%] mt-2 md:mt-0">
            <FormLabel className="md:py-3 py-1 text-black font-bold">
              Age
            </FormLabel>
            <TextField label="2 - 100" variant="outlined" />
          </Box>
          <Box className="md:flex items-center justify-evenly md:mt-auto md:w-[48%] mt-2   ">
            <Button
              variant="outlined"
              className="px-10 py-3 w-[95%] text-[16px]  border-[#FBAC18] mt-4 md:mt-0 hover:border-[#FBAC18]  bg-white outline-[#FBAC18] text-[#FBAC18] md:width-[150px]"
            >
              Clear
            </Button>
            <Link href="/homepages/bmicalculate/bmicalculate">
              <Button
                variant="filled"
                className="px-10 py-3 md:mx-[20px] w-[95%] text-[16px] bg-[#FBAC18] hover:bg-[#E09A15]  mt-4 md:mt-0 text-white md:width-[150px]"
              >
                Calculate
              </Button>
            </Link>
          </Box>
        </Box>
      </Box>
    </>
  );
};

export default BMI;
