import Head from 'next/head';
import HeaderJsx from '../components/home/Header';
import HeroSectionJsx from '../components/home/HeroSection';
import ResponsiveHeaderJsx from '../components/home/ResHeader';
import CategoryJsx from '../components/home/Category';
import BlogsJsx from '../components/home/Blogs';
import BMIJsx from '../components/home/BMI';
import GameJsx from '../components/home/Game';
import PlayingKidJsx from '../components/home/Playkid.jsx';
import DrinkJsx from '../components/home/Drink';
import FitnessJsx from '../components/home/Fitness';
import MobileAppJsx from '../components/home/Mobileapp';
import Footer from '../components/home/Footer';
export default function Home() {
  return (
    <>
      <Head>
        <title>FIT CORNERZ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./H_ResLogo.svg" />
      </Head>

      <ResponsiveHeaderJsx />
      <HeaderJsx />
      <HeroSectionJsx />
      <CategoryJsx />
      <BlogsJsx />
      <BMIJsx />
      <GameJsx />
      <PlayingKidJsx />
      <DrinkJsx />
      <FitnessJsx />
      <MobileAppJsx />
      <Footer />
    </>
  );
}
